### ISSUE TITLE
Decouple does not fall back to environment vars

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/cis#38]
Decouple should fall back to environment variables if settings.ini is not present.  

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/akrug/workspace/cis_functions/functions/validator/main.py", line 20, in <module>
    from cis import validation
  File "/Users/akrug/workspace/cis_functions/lib/python3.6/site-packages/cis/validation.py", line 8, in <module>
    from cis.encryption import decrypt
  File "/Users/akrug/workspace/cis_functions/lib/python3.6/site-packages/cis/encryption.py", line 7, in <module>
    from cis import settings
  File "/Users/akrug/workspace/cis_functions/lib/python3.6/site-packages/cis/settings.py", line 5, in <module>
    DYNAMODB_TABLE = config('CIS_DYNAMODB_TABLE')
  File "/Users/akrug/workspace/cis_functions/lib/python3.6/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/Users/akrug/workspace/cis_functions/lib/python3.6/site-packages/decouple.py", line 77, in __call__
    return self.get(*args, **kwargs)
  File "/Users/akrug/workspace/cis_functions/lib/python3.6/site-packages/decouple.py", line 64, in get
    raise UndefinedValueError('%s option not found and default value was not defined.' % option)
decouple.UndefinedValueError: CIS_DYNAMODB_TABLE option not found and default value was not defined.

**Comment by andrewkrug** [comment]
I was importing this wrong.
